#!/usr/bin/env python3
"""Generate native 35x35 icons for the macropad's built-in keycodes.

Source artwork: Lucide 0.468.0 (ISC). The tarball is passed explicitly.
"""
import argparse
import io
import tarfile
from pathlib import Path

import cairosvg
from PIL import Image, ImageDraw

SHARED_ICONS = {
    'cut': 'scissors', 'copy': 'copy', 'paste': 'paste',
    'previous_track': 'skip-back', 'play_pause': 'pause', 'next_track': 'skip-forward',
    'mute': 'volume-x', 'volume_up': 'volume-2',
    'arrow_up': 'arrow-up', 'arrow_down': 'arrow-down',
    'arrow_left': 'arrow-left', 'arrow_right': 'arrow-right',
    'word_prev': 'move-left', 'word_next': 'move-right',
    'mouse_up': 'move-up', 'mouse_down': 'move-down',
    'mouse_move_left': 'move-left', 'mouse_move_right': 'move-right',
}

ICONS = {
    'brightness_down': 'moon', 'brightness_up': 'sun',
    'control_panel': 'sliders-horizontal', 'computer': 'monitor',
    'web_search': 'globe', 'mail': 'mail',
    'calculator': 'calculator', 'volume_down': 'volume-1',
    'home': 'house', 'insert': 'file-input', 'end': 'corner-down-left',
    'delete': 'delete', 'screenshot': 'scan-eye',
    'mouse_left': 'mouse', 'mouse_middle': 'mouse', 'mouse_right': 'mouse',
    'wheel_up': 'chevrons-up', 'wheel_down': 'chevrons-down',
    'page_up': 'file-up', 'page_down': 'file-down',
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('lucide_tar', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    rows = []
    with tarfile.open(args.lucide_tar, 'r:gz') as archive:
        for name, source in ICONS.items():
            svg = archive.extractfile(f'package/icons/{source}.svg').read()
            # Match the thinner stroke of action icons while preserving size.
            svg = svg.replace(b'stroke-width="2"', b'stroke-width="1.7"')
            image = Image.open(io.BytesIO(cairosvg.svg2png(bytestring=svg, output_width=35, output_height=35))).convert('RGBA')
            if name.startswith('mouse_') and name in ('mouse_left', 'mouse_middle', 'mouse_right'):
                # A single mouse silhouette with the relevant button emphasized.
                draw = ImageDraw.Draw(image)
                region = {'mouse_left': (11, 12, 15, 17), 'mouse_middle': (16, 10, 19, 15), 'mouse_right': (20, 12, 24, 17)}[name]
                draw.rounded_rectangle(region, radius=1, fill=(0, 0, 0, 255))
            bits = [image.getpixel((x, y))[3] >= 72 for y in range(35) for x in range(35)]
            assert any(bits), name
            packed = bytes(sum(0x80 >> j for j in range(8) if i + j < len(bits) and bits[i + j]) for i in range(0, len(bits), 8))
            assert len(packed) == 154
            rows.append((name, packed))
    action_header = args.output.with_name('action_icons.h').read_text()
    action_names = __import__('re').findall(r'\{ // ([^\n]+)', action_header)
    assert len(action_names) >= 112
    lines = ['// Generated by tools/generate_builtin_key_icons.py from Lucide 0.468.0 (ISC).',
             '#pragma once', '#include <stdint.h>']
    for name, symbol in SHARED_ICONS.items():
        lines.append(f'#define EH_SHARED_ICON_{name.upper()} eh_action_icons[{action_names.index(symbol)}]')
    lines += ['enum eh_builtin_key_icon {']
    lines.extend(f'    EH_KEY_ICON_{name.upper()},' for name, _ in rows)
    lines += ['    EH_KEY_ICON_COUNT', '};',
              'static const uint8_t eh_builtin_key_icons[EH_KEY_ICON_COUNT][154] = {']
    for name, data in rows:
        lines.append(f'    {{ // {name}')
        lines.extend('        ' + ', '.join(f'0x{byte:02x}' for byte in data[i:i+16]) + ',' for i in range(0,154,16))
        lines.append('    },')
    lines.append('};')
    args.output.write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
